services:
  - docker

before_install:
- docker pull makeappdev/uselatex
- docker run -it -d --name uselatex makeappdev/uselatex bash
- docker ps -a
- docker exec uselatex bash -c "cmake --version; pdflatex --version"
- docker cp ./. uselatex:/

script:
- docker exec uselatex bash -c "mkdir -p build && cd build && cmake ..; make"
- mkdir -p export
- mkdir -p tmp
- echo "# This branch is for deployment only" >> export/README.md
- docker cp uselatex:build/. tmp
- cp tmp/*.pdf export
- cp tmp/git.id export

deploy:
  provider: pages
  skip-cleanup: true
  github-token: $GITHUB_TOKEN  # Set in travis-ci.org dashboard, marked secure
  local-dir: export
  on:
    branch: master

notifications:
  email: false
