dist: xenial
sudo: required

addons:
  apt:
    packages:
    - texlive-full
    - imagemagick

before_install:
- wget http://mirrors.ctan.org/macros/latex/contrib/titlesec.zip && unzip titlesec.zip
- sudo rm -r /usr/share/texlive/texmf-dist/tex/latex/titlesec
- sudo mv titlesec /usr/share/texlive/texmf-dist/tex/latex/
- wget https://gitlab.kitware.com/kmorel/UseLATEX/raw/master/UseLATEX.cmake
- CMAKE_ROOT=$(cmake --system-information | grep "CMAKE_ROOT " | cut -d' ' -f 2 | cut -d'"' -f2)
- sudo mv UseLATEX.cmake $CMAKE_ROOT/Modules/

install: true

script:
- mkdir -p build
- cd build && cmake ..; make; cd ..
- mkdir -p export && cp build/doc/*.pdf build/template-files/*.pdf build/git.id export
- echo "# This branch is for deployment only" >> export/README.md

deploy:
  provider: pages
  skip-cleanup: true
  github-token: $GITHUB_TOKEN  # Set in travis-ci.org dashboard, marked secure
  local-dir: export
  on:
    branch: master

notifications:
  email: false
  webhooks:
    urls:
      - https://webhooks.gitter.im/e/d1c80cd55c3503854852
    on_success: change  # options: [always|never|change] default: always
    on_failure: always  # options: [always|never|change] default: always
    on_start: never     # options: [always|never|change] default: always
